services:
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./certs:/root/.postgresql
    depends_on:
      - wait_for_db

  wait_for_db:
    image: busybox
    command: /bin/sh -c "until nc -z ${DB_HOST} ${DB_PORT}; do echo waiting for database; sleep 3; done;"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
