# Generated by Django 4.2.13 on 2024-06-08 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_githubtoken_githubrepo_githubrepo_unique_owner_repo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubCred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('token', models.CharField(max_length=250)),
                ('owner', models.CharField(max_length=100)),
                ('repo', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='githubcred',
            constraint=models.UniqueConstraint(fields=('owner', 'repo'), name='unique_github_cred'),
        ),
    ]
