# Generated by Django 4.2.11 on 2024-05-12 07:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_houstonuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="houstonuser",
            name="first_name",
            field=models.CharField(
                max_length=150,
                validators=[
                    django.core.validators.MinLengthValidator(
                        3, message="First name must have at least 3 characters"
                    ),
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z]*$", message="First name must contain only alphabets"
                    ),
                ],
            ),
        ),
    ]
